language: node_js
sudo: required
dist: bionic

addons:
  chrome: stable

services:
  - xvfb

git:
  depth: 10

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - npm install -g @blackbaud/skyux-cli

after_script:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/library-after-script.sh)

after_success:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/library-after-success.sh)
